version: '3.8'

services:
  investment-trading-service-test:
    image: investment-trading-service:test
    container_name: investment-trading-service-test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - T_INVEST_TEST_TOKEN=${T_INVEST_TEST_TOKEN}
      - TEST_DATABASE_URL=${TEST_DATABASE_URL:-jdbc:postgresql://localhost:5434/postgres?currentSchema=invest}
      - SPRING_DATASOURCE_TEST_USERNAME=${SPRING_DATASOURCE_TEST_USERNAME:-postgres}
      - SPRING_DATASOURCE_TEST_PASSWORD=${SPRING_DATASOURCE_TEST_PASSWORD:-123password123}
      - JAVA_OPTS=-Xmx1536m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    ports:
      - "8089:8089"
    networks:
      - investment-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8089/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  investment-network:
    driver: bridge

