version: '3.8'

# Использование:
# 1. Создайте .env.prod файл в корне проекта с переменными:
#    TINVEST_API_TOKEN=your_tinvest_token_here
#    DATABASE_URL=jdbc:postgresql://host.docker.internal:5434/postgres?currentSchema=invest
#    DATABASE_USERNAME=your_db_user
#    DATABASE_PASSWORD=your_db_password
# 2. Или установите переменные окружения перед запуском
# 3. Запустите: docker-compose -f docker-compose.prod.yml up -d --build

services:
  investment-trading-service-prod:
    image: investment-trading-service:prod
    container_name: investment-trading-service-prod
    build:
      context: .
      dockerfile: Dockerfile
    # Автоматически загружает переменные из .env.prod файла
    env_file:
      - .env.prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Токен T-Invest API - обязателен для работы приложения
      # Загружается из .env.prod файла или переменной окружения
      - TINVEST_API_TOKEN=${TINVEST_API_TOKEN}
      # Подключение к существующей БД
      # Вариант 1: Через host.docker.internal (Windows/Mac) - если БД на хосте или порт проброшен
      - DATABASE_URL=${DATABASE_URL:-jdbc:postgresql://host.docker.internal:5434/postgres?currentSchema=invest}
      # Вариант 2: Если БД в другом контейнере, укажите имя контейнера БД:
      # - DATABASE_URL=jdbc:postgresql://имя-контейнера-БД:5432/postgres?currentSchema=invest
      # И подключите контейнер к той же сети (см. комментарии ниже)
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - JAVA_OPTS=-Xmx1536m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    networks:
      - investment-network
    # Для доступа к БД на хосте через host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Если БД в другом контейнере, подключите к той же сети или используйте external_links:
    # external_links:
    #   - имя-контейнера-БД:postgres
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  investment-network:
    driver: bridge
    # Если БД в другой сети, раскомментируйте и подключите к внешней сети:
    # external:
    #   name: existing-db-network

